### ISSUE TITLE
运行python test.py IMGNET_PATH train ResNet-18_DBB_7101.pth -a ResNet-18 -t DBB出错，您知道这是什么原因吗

### ISSUE THREAD

**Issue by xiaoyudanaa** [DingXiaoH/DiverseBranchBlock#12]
![image](https://user-images.githubusercontent.com/77732714/114297582-f1357c00-9ae3-11eb-80b4-cd7c450d7976.png)

**Comment by DingXiaoH** [comment]
Fixed.
This is because Res18 was saved with torch 1.7, so the pth file was a zip archive.
I updated the files in Google drive and Baidu cloud.
Please download the latest files.

**Comment by xiaoyudanaa** [comment]
![image](https://user-images.githubusercontent.com/77732714/114485990-81d49f00-9c3f-11eb-8141-8147a9a78d37.png)

您好，我下载了您最新的文件，可依然是这个错误，您看一下

**Comment by DingXiaoH** [comment]
您好，这肯定不是最新的文件……
最新的文件是ResNet-18_DBB_7099.pth



***@***.***
 
发件人： xiaoyudanaa
发送时间： 2021-04-13 10:04
收件人： DingXiaoH/DiverseBranchBlock
抄送： DingXiaoH; Comment
主题： Re: [DingXiaoH/DiverseBranchBlock] 运行python test.py IMGNET_PATH train ResNet-18_DBB_7101.pth -a ResNet-18 -t DBB出错，您知道这是什么原因吗 (#12)
您好，我下载了您最新的文件，可依然是这个错误，您看一下
