### ISSUE TITLE
DiverseBranchBlock  在netron可视化出现的问题

### ISSUE THREAD

**Issue by Buildernet** [DingXiaoH/DiverseBranchBlock#19]
你好，我拜读了你这篇文章和19年的文章，并且使用netron可视化了你的base、ACB和DBB模块结构，我发现base和ACB都可以正常显示，但是DBB不对劲，方便留个微信或者QQ解决下这个问题吗，谢谢。

**Comment by Buildernet** [comment]
具体的问题是，我可视化你的DBB的BasicBlock，发现他并不是可视化了一个模块，好像是可视化了整个网络，我的可视化代码是
if __name__ == '__main__':
    model = BasicBlock(3, 3).cpu()
    img = torch.randn((2, 3, 256, 256)).cpu()

    output = model(img)

    onnx_path = "BasicBlock.onnx"
    torch.onnx.export(model, img, onnx_path, opset_version=10)
    netron.start(onnx_path)
    print(output.size())

**Comment by DingXiaoH** [comment]
你好，我不清楚netron的原理，我猜测这跟模块的具体结构应该没什么关系
