### ISSUE TITLE
关于TRANS Ⅲ的相关问题

### ISSUE THREAD

**Issue by jsczzzk** [DingXiaoH/DiverseBranchBlock#29]
大大您好，感谢您的nice work!
                我有一个疑问，您在TRANS Ⅲ中是先1x1,再3x3,那么这时候是需要在1x1后用当前的bias进行padding的。那么可否先3x3,再1x1，那么应该就不需要padding了吧。请问您当时有尝试过吗？

**Comment by DingXiaoH** [comment]
对的，先3x3再1x1就不用padding了，我试过，效果不如先1x1再3x3
