### ISSUE TITLE
用DBB block替换REPVGGblock，性能下降

### ISSUE THREAD

**Issue by DietDietDiet** [DingXiaoH/DiverseBranchBlock#6]
RT 主要是收敛速度和精度会比repVGG低一些

**Comment by DingXiaoH** [comment]
这很正常，因为identity没了。用在RepVGG上可以加个identity。

**Comment by CoinCheung** [comment]
@DietDietDiet 老哥，你试过加上identity吗，有提升迈

**Comment by CoinCheung** [comment]
@DingXiaoH 大佬你觉得如果在repvgg的基础上加上acnet的两个asymmetric-conv，再加上这个dbb的话，最后的性能会有提升吗

**Comment by DietDietDiet** [comment]
@CoinCheung 抱歉啊刚放假回来..精度和收敛比之前好多了，确实是Identity的问题，就是前向一次还是挺慢的，且显存开销蛮大的
@DingXiaoH repvgg加完identity之后在convert的时候像repvgg那样merge吗..回头老哥能不能更新个这样子的repvgg
